package ija.bluerock.labyrinth.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;


/**
 * Třída obsahující JFrame s menu. Třída zobrazuje celé menu a nabízí načtení/vytvoření nové hry.
 * @author Martin Kačmarčík
 */
public class MenuPanel extends javax.swing.JFrame {

    
    private int menuPosition;
    private int numberOfPlayers;
    private int fieldSize;
    private int numberOfTreasures;
    /**
     * Konstruktor třídy, který inicializuje jednotlivé komponenty a inicializuje proměnné.
     */
    public MenuPanel() {
        initComponents();
        menuPosition = 1;
        numberOfPlayers = -1;
        fieldSize = -1;
        numberOfTreasures = -1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        MenuLabel = new javax.swing.JLabel();
        NewGamePanel = new javax.swing.JPanel();
        NewGameHeader = new javax.swing.JLabel();
        NewGameBody = new javax.swing.JPanel();
        sizeOfField = new javax.swing.JComboBox();
        sizeOfFieldLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        numberOfPlayersCombo = new javax.swing.JComboBox();
        newGameBottomLabel = new javax.swing.JLabel();
        numberOfTreasuresLabel = new javax.swing.JLabel();
        numberOfTreasuresCombo = new javax.swing.JComboBox();
        newGameBottom = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Labyrinth - The Game");
        setBackground(new java.awt.Color(255, 135, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setPreferredSize(new java.awt.Dimension(650, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 700));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyHandler(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 135, 0));
        mainPanel.setMinimumSize(new java.awt.Dimension(1000, 650));
        mainPanel.setName(""); // NOI18N
        mainPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainPanelKeyPressed(evt);
            }
        });
        mainPanel.setLayout(new java.awt.CardLayout());

        MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_1b.png"))); // NOI18N
        MenuLabel.setPreferredSize(new java.awt.Dimension(650, 650));
        mainPanel.add(MenuLabel, "card2");

        NewGamePanel.setBackground(new java.awt.Color(255, 137, 0));

        NewGameHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/topmenu.png"))); // NOI18N

        NewGameBody.setBackground(new java.awt.Color(255, 135, 0));

        sizeOfField.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        sizeOfField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5", "7", "9", "11" }));
        sizeOfField.setSelectedIndex(1);
        sizeOfField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeOfFieldActionPerformed(evt);
            }
        });

        sizeOfFieldLabel.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        sizeOfFieldLabel.setText("Velikost hrací plochy");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        jLabel1.setText("Počet hráčů");

        numberOfPlayersCombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        numberOfPlayersCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));
        numberOfPlayersCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfPlayersComboActionPerformed(evt);
            }
        });

        newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame2.png"))); // NOI18N

        numberOfTreasuresLabel.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        numberOfTreasuresLabel.setText("Počet pokladů");

        numberOfTreasuresCombo.setFont(new java.awt.Font("Times New Roman", 0, 22)); // NOI18N
        numberOfTreasuresCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "24" }));
        numberOfTreasuresCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfTreasuresComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewGameBodyLayout = new javax.swing.GroupLayout(NewGameBody);
        NewGameBody.setLayout(NewGameBodyLayout);
        NewGameBodyLayout.setHorizontalGroup(
            NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewGameBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newGameBottomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(NewGameBodyLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sizeOfFieldLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NewGameBodyLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(sizeOfField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(NewGameBodyLayout.createSequentialGroup()
                        .addComponent(numberOfPlayersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270)
                        .addComponent(numberOfTreasuresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))
                    .addGroup(NewGameBodyLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139)
                        .addComponent(numberOfTreasuresLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
        );
        NewGameBodyLayout.setVerticalGroup(
            NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGameBodyLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeOfFieldLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberOfTreasuresLabel))
                .addGap(18, 18, 18)
                .addGroup(NewGameBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfTreasuresCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sizeOfField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfPlayersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106)
                .addComponent(newGameBottomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout newGameBottomLayout = new javax.swing.GroupLayout(newGameBottom);
        newGameBottom.setLayout(newGameBottomLayout);
        newGameBottomLayout.setHorizontalGroup(
            newGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        newGameBottomLayout.setVerticalGroup(
            newGameBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout NewGamePanelLayout = new javax.swing.GroupLayout(NewGamePanel);
        NewGamePanel.setLayout(NewGamePanelLayout);
        NewGamePanelLayout.setHorizontalGroup(
            NewGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGamePanelLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(NewGameHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewGamePanelLayout.createSequentialGroup()
                .addComponent(NewGameBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newGameBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NewGamePanelLayout.setVerticalGroup(
            NewGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGamePanelLayout.createSequentialGroup()
                .addComponent(NewGameHeader)
                .addGroup(NewGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewGamePanelLayout.createSequentialGroup()
                        .addGap(510, 510, 510)
                        .addComponent(newGameBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewGamePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(NewGameBody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(NewGamePanel, "card4");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Key handler, který se stará o celou navigaci skrz menu.
     * Handler na základě stisknuté klávesy posouvá pozici v konečném automatu a vybírá přislušné akce.
     * @param evt Key event parametr.
     */
    private void KeyHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyHandler
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        {
            /* the Nova hra button */
            if(menuPosition == 1){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_3.png")));
                menuPosition = 3;
            }
            /* the Autori button */
            else if(menuPosition == 2){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_1.png")));
                menuPosition = 1;
            }
            /* the Konec button */
            else if(menuPosition == 3){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_2.png")));
                menuPosition = 2;
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            /* the Nova hra button */
            if(menuPosition == 1){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_2.png")));
                menuPosition = 2;
            }
            /* the Autori button */
            else if(menuPosition == 2){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_3.png")));
                menuPosition = 3;
            }
            /* the Konec button */
            else if(menuPosition == 3){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_1.png")));
                menuPosition = 1;
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            /* the Nova hra button */
            if(menuPosition == 1){
                menuPosition = 7;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame2.png")));
                Container parent = MenuLabel.getParent();
                parent.removeAll();
                parent.add(NewGamePanel);
                parent.repaint();
                parent.revalidate();

            }
            /* the Autori button */
            else if(menuPosition == 2){
                menuPosition = 4;
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/readme.png")));
            }
            /* the Konec button */
            else if(menuPosition == 3){
                System.exit(0);
            }
            /* the Zpet in Autori button */
            else if(menuPosition == 4){
                MenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/menu_volba_1.png")));
                menuPosition = 1;
            }
            /* the Zpet button */
            else if(menuPosition == 5){
                // TODO add your handling code here:
                mainPanel.removeAll();
                mainPanel.add(MenuLabel);
                mainPanel.repaint();
                mainPanel.revalidate();
                mainPanel.requestFocusInWindow();
                menuPosition = 1;
            }
            /* the OK in new game button */
            else if(menuPosition == 7){
                fieldSize = Integer.parseInt(sizeOfField.getSelectedItem().toString());
                numberOfPlayers = Integer.parseInt(numberOfPlayersCombo.getSelectedItem().toString());
                numberOfTreasures = Integer.parseInt(numberOfTreasuresCombo.getSelectedItem().toString());
                this.setVisible(false);
                new GameWindow(this, fieldSize, numberOfPlayers, numberOfTreasures, 1, null);
            }
            else if(menuPosition == 6){
                new SaveGame(null, 2, this, null).setVisible(true);
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            if(menuPosition == 5){
                menuPosition = 7;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame2.png")));
            }
            else if(menuPosition == 6)
            {
                menuPosition = 5;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame1.png")));
            }
            else if(menuPosition == 7){
                menuPosition = 6;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame3.png")));
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_LEFT)
        {
            /* the Zpet button */
            if(menuPosition == 5){
                menuPosition = 6;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame3.png")));
            }
            /* the OK button */
            else if(menuPosition == 6)
            {
                menuPosition = 7;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame2.png")));
            }
            else if(menuPosition == 7)
            {
                menuPosition = 5;
                newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame1.png")));
            }
        }
        mainPanel.requestFocusInWindow();
    }//GEN-LAST:event_KeyHandler
    /**
     * Generovaná metoda, která se stará o stisknuté klávesy v hlavním panelu a přeposílá je do hlavního KeyHandleru.
     * @param evt Key event evt.
     */
    private void mainPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainPanelKeyPressed
        // TODO add your handling code here:
        KeyHandler(evt);
        mainPanel.requestFocusInWindow();
    }//GEN-LAST:event_mainPanelKeyPressed
    /**
     * Metoda pouze nastavuje správný focus pro správné fungování pohybu pomocí kláves.
     * @param evt Action event evt.
     */
    private void numberOfTreasuresComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfTreasuresComboActionPerformed
        // TODO add your handling code here:
        mainPanel.requestFocusInWindow();
    }//GEN-LAST:event_numberOfTreasuresComboActionPerformed
    /**
     * Metoda pouze nastavuje správný focus pro správné fungování pohybu pomocí kláves.
     * @param evt Action event evt.
     */
    private void numberOfPlayersComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfPlayersComboActionPerformed
        // TODO add your handling code here:
        mainPanel.requestFocusInWindow();
    }//GEN-LAST:event_numberOfPlayersComboActionPerformed
    /**
     * Metoda pouze nastavuje správný focus pro správné fungování pohybu pomocí kláves.
     * @param evt Action event evt.
     */
    private void sizeOfFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeOfFieldActionPerformed
        // TODO add your handling code here:
        mainPanel.requestFocusInWindow();
    }//GEN-LAST:event_sizeOfFieldActionPerformed


    /**
     * Hlavní main třída, která je spuštěna při startu programu.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPanel().setVisible(true);
            }
        });
    }
    
    /**
     * Funkce, která je volána při návratu do hl. menu ze hry. Stará se o správné vykreslování hlavního menu.
     */
    public void getBackToMenu(){
        newGameBottomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu/bottomNewGame2.png")));
        mainPanel.removeAll();
        mainPanel.add(MenuLabel);
        mainPanel.repaint();
        mainPanel.revalidate();
        mainPanel.requestFocusInWindow();
        menuPosition = 1;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuLabel;
    private javax.swing.JPanel NewGameBody;
    private javax.swing.JLabel NewGameHeader;
    private javax.swing.JPanel NewGamePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel newGameBottom;
    private javax.swing.JLabel newGameBottomLabel;
    private javax.swing.JComboBox numberOfPlayersCombo;
    private javax.swing.JComboBox numberOfTreasuresCombo;
    private javax.swing.JLabel numberOfTreasuresLabel;
    private javax.swing.JComboBox sizeOfField;
    private javax.swing.JLabel sizeOfFieldLabel;
    // End of variables declaration//GEN-END:variables
}
