package ija.bluerock.labyrinth.gui;

import ija.bluerock.labyrinth.game.Game;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 * Třída obsahující jednoduché Save/Load okénko. 
 * @author Martin Kačmarčík
 */
public class SaveGame extends javax.swing.JFrame {
    private int pozice = 1;
    private Game game;
    private int mode;
    private MenuPanel menu;
    private boolean proselNeprosel = true;
    private GameWindow window;
    /**
     * Konstruktor třídy, který inicializuje třídní proměnné, nastaví komponenty a nastaví focus.
     * @param game  Parametr obsahující třídu se hrou.
     * @param mode  Mod - 1 - Uložení hry, 2 - Načítání hry.
     * @param menu  Parametr obsahující třídu s menu, aby ji mohla třída dle potřeby zavřít, ukázat.
     * @param window Parametr obsahující třídu se hrou, v případě, že se načítá ze hry.
     */
    public SaveGame(Game game, int mode, MenuPanel menu, GameWindow window) {
        this.game = game;
        this.mode = mode;
        this.menu = menu;
        this.window = window;
        initComponents();
        if(mode == 1){
            //save game
            jLabel2.setText("Uložení hry");
        }
        else if(mode == 2){
            jLabel2.setText("Načtení hry");
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loadGameIcon.png")));
        }
        exitButton.setBorder(BorderFactory.createEmptyBorder());
        exitButton.setContentAreaFilled(false);
        bodySavePanel.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topSavePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        bodySavePanel = new javax.swing.JPanel();
        bodySaveLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 135, 0));

        topSavePanel.setBackground(new java.awt.Color(255, 135, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGameIcon.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 25)); // NOI18N
        jLabel2.setText("ULOŽENÍ HRY");

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topSavePanelLayout = new javax.swing.GroupLayout(topSavePanel);
        topSavePanel.setLayout(topSavePanelLayout);
        topSavePanelLayout.setHorizontalGroup(
            topSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topSavePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        topSavePanelLayout.setVerticalGroup(
            topSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topSavePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topSavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bodySavePanel.setBackground(new java.awt.Color(255, 169, 0));
        bodySavePanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bodySavePanelHandler(evt);
            }
        });

        bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz1.png"))); // NOI18N

        javax.swing.GroupLayout bodySavePanelLayout = new javax.swing.GroupLayout(bodySavePanel);
        bodySavePanel.setLayout(bodySavePanelLayout);
        bodySavePanelLayout.setHorizontalGroup(
            bodySavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodySaveLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodySavePanelLayout.setVerticalGroup(
            bodySavePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodySavePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bodySaveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(topSavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodySavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topSavePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodySavePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Generovaný ActionEvent listener, který má na starosti exit tlačítko.
     * @param evt Action event evt.
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.requestFocusInWindow();
    }//GEN-LAST:event_exitButtonActionPerformed
    /**
     * Handler přepínající mezi jednotlivými uloženými pozicemi.
     * @param evt Key event parametr.
     */
    private void bodySavePanelHandler(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bodySavePanelHandler

        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            if(mode == 1){
                try {
                    game.saveGame(pozice);
                } catch (IOException ex){System.out.println("Chyba pri ulozeni hry."); System.exit(88);}  
                JOptionPane.showMessageDialog(null, "Hra uložena");
                this.setVisible(false);
            }          
            else if(mode == 2){
                try {
                    game = Game.loadGame(pozice);                    
                } catch (Exception ex){JOptionPane.showMessageDialog(null, "Chyba pri nacteni hry."); proselNeprosel = false;}  
                if(proselNeprosel == true){
                    new GameWindow(this.menu, 0, 0, 0, 2, game);                   
                    JOptionPane.showMessageDialog(null, "Hra úspěšně načtena");
                    this.setVisible(false);
                    if(window != null){
                        window.setVisible(false);
                    }
                    menu.setVisible(false);
                }
                proselNeprosel = true;
            }          
            bodySavePanel.requestFocusInWindow();
        }
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        {
            //prvni pozice k ulozeni
            if(pozice == 1){
                pozice = 3;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz3.png")));
            }
            //druha pozice k ulozeni
            else if(pozice == 2){
                pozice = 1;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz1.png")));
            }
            //treti pozice k ulozeni
            else if(pozice == 3){
                pozice = 2;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz2.png")));
            }
        }
        else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            //prvni pozice k ulozeni
            if(pozice == 1){
                pozice = 2;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz2.png")));
            }
            //druha pozice k ulozeni
            else if(pozice == 2){
                pozice = 3;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz3.png")));
            }
            //treti pozice k ulozeni
            else if(pozice == 3){
                pozice = 1;
                bodySaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/saveGame/saveGamePoz1.png")));
            }
        }        
    }//GEN-LAST:event_bodySavePanelHandler

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodySaveLabel;
    private javax.swing.JPanel bodySavePanel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel topSavePanel;
    // End of variables declaration//GEN-END:variables
}
